FROM apache/airflow:2.11.0

USER airflow

ARG AIRFLOW_VERSION=2.11.0
# Airflow 2.11 預設 Python 3.12
ARG PYTHON_VERSION=3.12
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

COPY --chown=airflow:root requirements.airflow.txt /requirements.txt

# 提高安裝穩定性
ENV PIP_DEFAULT_TIMEOUT=1200 PIP_DISABLE_PIP_VERSION_CHECK=1
RUN pip install --no-cache-dir -r /requirements.txt --constraint "${CONSTRAINT_URL}"
