# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.
# See the NOTICE file for details.
# -----------------------------------------------------------------------------
# 20251024_001 - PoChun Hsu
# [Merged] Integrate Spark, RedisInsight, builder, and GCP key support from Airflow 2.11.0 into 3.1.0 structure.
# -----------------------------------------------------------------------------
# 20260309_001 - PoChun Hsu - [Add]  DBT
# 20260310_001 - PoChun Hsu - [Add]  port for DBT
# 20260330_001 - PoChun Hsu - [Add]  Iceberg and MinIO (Simulate S3)

---
x-airflow-common:
  &airflow-common
  image: local/airflow:3.1.0-pc1
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    # -------------------------------
    # Added from Airflow 2.11.0
    # -------------------------------
    GCP_KEY_PATH: /opt/airflow/keys/starry-center-405211-04dd3e1fa083.json
    GCP_PROJECT: starry-center-405211
    GCP_SCOPE: https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/drive

    # -------------------------------
    # Enable directly copy log from Web UI
    # -------------------------------
    AIRFLOW__LOGGING__LOG_FETCH_TIMEOUT_SEC: '0'
    AIRFLOW__LOGGING__LOG_FETCH_DELAY_SEC: '0'

  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/scripts:/opt/airflow/scripts:ro
    - ${AIRFLOW_PROJ_DIR:-.}/airflow/keys:/opt/airflow/keys:ro
    - /var/run/docker.sock:/var/run/docker.sock   # ★ 新增：允許 DockerOperator/Spark trigger
    #- ${AIRFLOW_PROJ_DIR:-.}:/opt/project:ro
    #- ./:/opt/project:rw
    - /Users/sherryli/Desktop/MacShop/airflow3-docker:/Users/sherryli/Desktop/MacShop/airflow3-docker:rw
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

x-spark-common: &spark-common
  image: local/spark:3.5.0

services:
  # -------------------------------------
  # Core Services
  # -------------------------------------
  postgres:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  redis:
    image: redis:7.2-bookworm
    expose: ["6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    ports: ["5540:5540"]
    depends_on:
      - redis

  # -------------------------------------
  # Airflow Components
  # -------------------------------------
  airflow-apiserver:
    <<: *airflow-common
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    image: local/airflow:3.1.0-pc1
    command: api-server
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    user: "0:0"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    user: "0:0"
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  # -------------------------------------
  # Spark Stack (from 2.11.0)
  # -------------------------------------
  spark-master:
    build:
      context: .
      dockerfile: ./spark/Dockerfile
    image: local/spark:3.5.0
    container_name: spark
    command: ["/bin/bash","-lc","/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_MODE=master
      - SPARK_HOME=/opt/spark
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8088:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./spark_app:/opt/spark-apps
      - ./spark_conf:/opt/spark/conf
      - ./spark-events:/tmp/spark-events
    depends_on:
      - iceberg-rest
      - minio


  spark-thrift:
    <<: *spark-common
    command: >
      bash -c "
      /opt/spark/sbin/start-thriftserver.sh
      --master spark://spark:7077
      "
    ports:
      - "10000:10000"
    volumes:
      - ./spark_conf:/opt/spark/conf
      - ./spark-events:/tmp/spark-events
    depends_on:
      - spark-master

  spark-init:
    <<: *spark-common
    volumes:
      - ./spark_app:/opt/spark-apps
      - ./spark_conf:/opt/spark/conf
    command: >
      bash -c "
      sleep 10 &&
      /opt/spark/bin/spark-sql \
        --master spark://spark:7077 \
        -f /opt/spark-apps/init.sql
      "
    depends_on:
      - spark-master

  spark-worker:
    <<: *spark-common
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark:7077
      "
    environment:
      - SPARK_MODE=worker
      - SPARK_HOME=/opt/spark
    volumes:
      - ./spark_conf:/opt/spark/conf
      - ./spark-events:/tmp/spark-events
    depends_on:
      - spark-master

  spark-history:
    <<: *spark-common
    command: ["/bin/bash","-lc","/opt/spark/sbin/start-history-server.sh"]
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/tmp/spark-events
      - SPARK_HOME=/opt/spark
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/tmp/spark-events:ro

  # 20260309_001 >>
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    platform: linux/amd64
    container_name: dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
    ports:
      - "8081:8080" # 20260310_001
    environment:
      PIP_ADDITIONAL_REQUIREMENTS: "dbt-metricflow"
    depends_on:
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true
    entrypoint: ["/bin/sh", "-c"]
    command: ["dbt docs generate && dbt docs serve --port 8080 --host 0.0.0.0"]
  # 20260309_001 <<
  
  # 20260330_001 >>
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio_data:/data

  iceberg-rest:
    image: tabulario/iceberg-rest
    ports:
      - "8181:8181"
    environment:
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO

      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_REGION: us-east-1

      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_ACCESS__KEY__ID: admin
      CATALOG_S3_SECRET__ACCESS__KEY: admin123
      CATALOG_S3_PATH__STYLE__ACCESS: "true"
      CATALOG_S3_REGION: us-east-1
    depends_on:
      - minio
  # 20260330_001 <<

  # -------------------------------------
  # Builders (for reproducible builds)
  # -------------------------------------
  airflow-builder:
    image: local/airflow:3.1.0-pc1
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    profiles: ["builder"]
    volumes:
      - ./keys:/opt/airflow/keys:ro

  # -------------------------------------
  # Initialization
  # -------------------------------------
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: "/opt/airflow/scripts/airflow-init.sh"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
      GCP_KEY_PATH: /opt/airflow/keys/starry-center-405211-04dd3e1fa083.json
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  flower:
    <<: *airflow-common
    command: celery flower
    profiles: ["flower"]
    ports: ["5555:5555"]
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres-db-volume:
  metabase-data:
